from __future__ import annotations

import html
import io
import json
import re
import zipfile
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st
import streamlit.components.v1 as components


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "output"
SVG_DIR = OUTPUT / "svg"
SVG_PNG_DIR = OUTPUT / "svg_png"      # SVG → PNG 预渲染图（用户可直接查看，无需浏览器）
REPORT_DIR = OUTPUT / "reports"

LINES = ["LINE215", "LINE216"]

SVG_INFO = {
    "LINE215_single_line.svg": ("LINE215 单馈线单线图", "根据线路拓扑自动生成，展示线路设备及连接关系"),
    "LINE216_single_line.svg": ("LINE216 单馈线单线图", "根据线路拓扑自动生成，展示线路设备及连接关系"),
    "10kVLINE111_tie.svg": ("10kVLINE111 馈线联络图", "识别馈线间联络关系并突出联络开关"),
    "SUB004_station_tie.svg": ("SUB004 全站联络总图", "以 SUB004 为中心展示站内馈线及跨线联络关系"),
    "TMP00034205_power_trace.svg": ("TMP00034205 电源追溯图", "从目标设备反向追踪主供电路径与备用路径"),
    "LINE215_beautified.svg": ("LINE215 标准化美化图", "保留设备元数据，对图形布局和标注进行规范化"),
    "LINE216_beautified.svg": ("LINE216 标准化美化图", "保留设备元数据，对图形布局和标注进行规范化"),
    "LINE215_add_station_000300.svg": ("LINE215 增加站房验证图", "用于展示增补设备后的拓扑变化"),
    "LINE216_del_switch_00024.svg": ("LINE216 删除开关验证图", "用于展示设备调整后的拓扑变化"),
}

KEY_LABELS = {
    "score_before": "修复前评分",
    "score_after": "复核评分",
    "total_deduction": "扣分合计",
    "defect_count": "缺陷数量",
    "deterministic_repair_ratio": "确定性修复比例",
    "defect_type": "缺陷类型",
    "device_id": "设备编号",
    "equip_id": "设备编号",
    "target_equip": "目标设备",
    "device_name": "设备名称",
    "risk_level": "风险等级",
    "confidence": "置信度",
    "suggestion": "修复建议",
    "action": "修复动作",
    "impact_summary": "影响说明",
    "repair_id": "方案编号",
    "description": "问题说明",
    "detail": "详细信息",
    "rule_code": "规则编号",
}


def decode(raw: bytes) -> str:
    for encoding in ("utf-8-sig", "gb18030", "gbk"):
        try:
            return raw.decode(encoding)
        except UnicodeDecodeError:
            continue
    return raw.decode("utf-8", errors="replace")


def prepare_inline_svg(raw: bytes) -> str:
    """Convert XML namespace prefixes into browser-friendly inline SVG tags."""
    text = decode(raw)
    text = re.sub(r"<\?xml[^>]*\?>", "", text, count=1, flags=re.IGNORECASE)
    text = re.sub(r"xmlns:ns\d+=", "xmlns=", text)
    return re.sub(r"(<\/?)(?:ns\d+):", r"\1", text)


def clean_text(value: Any) -> str:
    text = "" if value is None else str(value)
    if "\ufffd" in text or "锟斤拷" in text:
        return "原始文件未提供有效中文说明"
    return text.replace("?", "—").replace("\ufeff", "").strip()


def clean_data(value: Any) -> Any:
    if isinstance(value, dict):
        return {KEY_LABELS.get(str(k), clean_text(k)): clean_data(v) for k, v in value.items() if k != "note"}
    if isinstance(value, list):
        return [clean_data(v) for v in value]
    if isinstance(value, str):
        return clean_text(value)
    return value


def load_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    try:
        return clean_data(json.loads(decode(path.read_bytes())))
    except Exception:
        return default


def raw_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default


def generated_excel_files() -> list[Path]:
    """Read Excel reports generated by main.py in the output directory."""
    return sorted(
        (path for path in OUTPUT.glob("*.xlsx") if path.is_file()),
        key=lambda path: path.name.lower(),
    )


def zip_files(files: list[Path]) -> bytes:
    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as archive:
        for path in files:
            if path.exists() and path.is_file():
                archive.write(path, path.name)
    return buffer.getvalue()


def raw_json(path: Path, default: Any = None) -> Any:
    if not path.exists():
        return default
    try:
        return json.loads(decode(path.read_bytes()))
    except Exception:
        return default


def style() -> None:
    st.markdown(
        """
        <style>
        html, body, [class*="css"], .stApp {font-family:"Microsoft YaHei UI","Microsoft YaHei","PingFang SC",sans-serif;}
        .stApp {background:#f4f7fb;color:#17243a;}
        [data-testid="stHeader"] {background:transparent;}
        [data-testid="stSidebar"] {background:#ffffff;border-right:1px solid #e8e8e8;}
        [data-testid="stSidebar"] * {color:#3f4b59;}
        [data-testid="stSidebar"] .stRadio label {padding:8px 10px;border-radius:7px;margin:2px 0;}
        [data-testid="stSidebar"] .stRadio label:hover {background:rgba(255,255,255,.10);}
        .block-container {max-width:1500px;padding-top:1rem;padding-bottom:3rem;}
        .topbar {background:linear-gradient(135deg,#1890ff,#00a854);border-radius:0;padding:20px 28px;margin:-1rem -1rem 18px;color:#fff;}
        .topbar h1 {font-size:25px;margin:0;color:#fff;letter-spacing:.5px;}
        .topbar p {margin:7px 0 0;color:rgba(255,255,255,.92);font-size:13px;}
        .section {font-size:20px;font-weight:700;color:#183b64;margin:12px 0 12px;border-left:4px solid #e99b37;padding-left:10px;}
        .card {background:#fff;border:1px solid #e1e8f0;border-radius:6px;padding:17px 18px;min-height:116px;box-shadow:0 3px 10px rgba(28,55,90,.05);}
        .card b {display:block;color:#183b64;font-size:16px;margin-bottom:7px;}
        .card p {color:#66788e;font-size:13px;line-height:1.7;margin:0;}
        .metric {background:#fff;border:1px solid #e8e8e8;border-radius:7px;padding:15px 17px;border-bottom:3px solid #1890ff;}
        .metric span {font-size:13px;color:#718096;}.metric strong {display:block;font-size:25px;color:#183b64;margin-top:4px;}
        .flow {background:#eef4fa;border:1px solid #d6e2ee;border-radius:6px;padding:15px 18px;color:#314964;line-height:1.8;font-size:14px;}
        .flow strong {color:#183b64;}.arrow {color:#d47d18;padding:0 8px;font-weight:700;}
        .svgbox {background:#fff;border:1px solid #d6e0ea;border-radius:6px;padding:8px;}
        .file-row {background:#fff;border:1px solid #e1e8f0;border-radius:5px;padding:10px 12px;margin:5px 0;color:#42566e;font-size:13px;}
        .tag {display:inline-block;background:#e8f1fb;color:#245b91;border-radius:3px;padding:3px 7px;margin-right:5px;font-size:12px;}
        .plain-note {color:#6b7c90;font-size:13px;line-height:1.7;}
        div[data-testid="stTabs"] button {font-weight:600;}
        div[data-testid="stTabs"] button[aria-selected="true"] {color:#1890ff;}
        div[data-testid="stDataFrame"] {background:#fff;border-radius:6px;}
        </style>
        """,
        unsafe_allow_html=True,
    )


def header() -> None:
    st.markdown(
        """
        <div class="topbar">
          <h1>主配网拓扑校验与图形成果展示</h1>
          <p>电力拓扑与图模校验技术竞赛 · 拓扑校验、缺陷定位、修复建议与 SVG 成果</p>
        </div>
        """,
        unsafe_allow_html=True,
    )


def section(title: str) -> None:
    st.markdown(f'<div class="section">{html.escape(title)}</div>', unsafe_allow_html=True)


def cards(items: list[tuple[str, str]]) -> None:
    cols = st.columns(len(items))
    for col, (title, body) in zip(cols, items):
        with col:
            st.markdown(f'<div class="card"><b>{html.escape(title)}</b><p>{html.escape(body)}</p></div>', unsafe_allow_html=True)


def metrics(items: list[tuple[str, str]]) -> None:
    cols = st.columns(len(items))
    for col, (label, value) in zip(cols, items):
        with col:
            st.markdown(f'<div class="metric"><span>{html.escape(label)}</span><strong>{html.escape(value)}</strong></div>', unsafe_allow_html=True)


def line_bundle(line: str) -> dict[str, Any]:
    score_raw = raw_json(OUTPUT / f"{line}_质量评分与可解释置信度报告.json", {}) or {}
    score = clean_data(score_raw)
    defects = load_json(OUTPUT / f"{line}_缺陷清单报告.json", []) or []
    repair = load_json(OUTPUT / f"{line}_最小修改候选与SQL草案.json", {}) or {}
    breakpoint = load_json(OUTPUT / f"{line}_赛题1.2专项断点报告.json", {}) or {}
    sql_path = OUTPUT / f"{line}_正向修复与回滚脚本.sql"
    sql = clean_text(decode(sql_path.read_bytes())) if sql_path.exists() else ""
    raw_summary = score_raw.get("score_summary", {})
    return {"score": score, "raw_summary": raw_summary, "defects": defects, "repair": repair, "breakpoint": breakpoint, "sql": sql}


def overview_page() -> None:
    section("项目内容")
    cards([
        ("拓扑结构校验", "检测设备悬空、线路断点、联络开关及合环问题，定位到设备和线路。"),
        ("图模一致性比对", "比较 SVG 图形与数据库模型，识别图有模无、模有图无及连接不一致。"),
        ("修复方案生成", "结合风险、置信度和影响范围给出最小修改候选，并生成正向与回滚 SQL。"),
        ("SVG 图形成果", "形成馈线单线图、联络关系图、全站联络图、电源追溯图及美化图。"),
    ])

    section("输入与输出")
    st.markdown(
        """
        <div class="flow"><strong>输入</strong>　SQL 设备模型、端点关系、线路信息、遥信遥测数据、配网 SVG 图纸
        <span class="arrow">→</span><strong>分析</strong>　拓扑建图、连通性检测、图模比对、电气逻辑校验、置信度评估
        <span class="arrow">→</span><strong>输出</strong>　缺陷清单、评分报告、修复候选、SQL 脚本、Excel 报告、SVG 图形</div>
        """,
        unsafe_allow_html=True,
    )

    section("现有成果")
    metrics([("重点线路", "2 条"), ("缺陷记录", "6,987 条"), ("修复候选", "6,987 条"), ("SVG 成果", "10 幅")])
    st.markdown("<br>", unsafe_allow_html=True)
    cards([
        ("LINE215", "已生成缺陷清单、质量评分、专项断点报告、修复候选、SQL 脚本、Excel 报告及多类 SVG。"),
        ("LINE216", "已生成缺陷清单、质量评分、专项断点报告、修复候选、SQL 脚本、Excel 报告及多类 SVG。"),
        ("专题图形", "包含 10kVLINE111 联络图、SUB004 全站联络图和 TMP00034205 电源追溯图。"),
    ])


def line_page() -> None:
    section("线路校验成果")
    line = st.selectbox("线路", LINES, label_visibility="collapsed")
    bundle = line_bundle(line)
    summary = bundle["raw_summary"]
    defects = bundle["defects"] if isinstance(bundle["defects"], list) else []
    candidates = bundle["repair"].get("candidates", []) if isinstance(bundle["repair"], dict) else []
    metrics([
        ("线路", line),
        ("缺陷数量", f"{len(defects):,}"),
        ("修复候选", f"{len(candidates):,}"),
        ("确定性修复比例", f"{float(summary.get('deterministic_repair_ratio', 0)) * 100:.0f}%"),
    ])
    tabs = st.tabs(["缺陷清单", "修复候选", "评分结果", "专项断点", "SQL 脚本", "Excel 报告"])
    with tabs[0]:
        if defects:
            df = pd.DataFrame(defects)
            st.dataframe(df, use_container_width=True, height=560, hide_index=True)
        else:
            st.info("该线路暂无缺陷记录")
    with tabs[1]:
        if candidates:
            st.dataframe(pd.DataFrame(candidates), use_container_width=True, height=560, hide_index=True)
        else:
            st.info("该线路暂无修复候选")
    with tabs[2]:
        st.json(bundle["score"], expanded=2)
    with tabs[3]:
        st.json(bundle["breakpoint"], expanded=2)
    with tabs[4]:
        st.code(bundle["sql"] or "该线路暂无 SQL 脚本", language="sql", line_numbers=True)
    with tabs[5]:
        xlsx = OUTPUT / f"{line}_拓扑校验缺陷报告.xlsx"
        if xlsx.exists():
            st.markdown(f'<div class="file-row"><span class="tag">Excel</span>{html.escape(xlsx.name)}　{xlsx.stat().st_size / 1024:.1f} KB</div>', unsafe_allow_html=True)
            st.download_button("下载线路报告", xlsx.read_bytes(), xlsx.name, use_container_width=True)
        else:
            st.info("运行主程序后，线路 Excel 报告会显示在这里。")


def svg_page() -> None:
    section("SVG 图形成果")
    files = sorted(SVG_DIR.glob("*.svg"), key=lambda p: p.name.lower())
    if not files:
        st.info("暂无 SVG 图形成果")
        return
    selected = st.selectbox("选择线路或图形", files, format_func=lambda p: SVG_INFO.get(p.name, (p.stem, ""))[0])
    title, desc = SVG_INFO.get(selected.name, (selected.stem, "项目生成的 SVG 图形成果"))

    # 优先尝试 PNG 回退（用户无需浏览器即可查看）
    png_candidate = SVG_PNG_DIR / selected.name.replace(".svg", ".png")
    has_png = png_candidate.exists()

    left, right = st.columns([0.23, 0.77], gap="large")
    with left:
        st.markdown(f'<div class="card"><b>{html.escape(title)}</b><p>{html.escape(desc)}</p></div>', unsafe_allow_html=True)
        st.markdown(f'<div class="file-row"><span class="tag">SVG</span>{html.escape(selected.name)}</div>', unsafe_allow_html=True)
        if has_png:
            st.markdown(f'<div class="file-row"><span class="tag">PNG</span>{html.escape(png_candidate.name)}　{png_candidate.stat().st_size / 1024:.1f} KB</div>', unsafe_allow_html=True)
        st.markdown(f'<div class="file-row">文件大小　{selected.stat().st_size / 1024:.1f} KB</div>', unsafe_allow_html=True)
        if has_png:
            with open(png_candidate, "rb") as f:
                st.download_button("下载 PNG", f.read(), png_candidate.name, mime="image/png", use_container_width=True)
        with open(selected, "rb") as f:
            st.download_button("下载 SVG", f.read(), selected.name, mime="image/svg+xml", use_container_width=True)
    with right:
        if has_png:
            st.image(str(png_candidate), use_container_width=True)
        else:
            raw_svg = prepare_inline_svg(selected.read_bytes())
            components.html(f'<div class="svgbox" style="height:720px;overflow:auto">{raw_svg}</div>', height=750, scrolling=True)


def _png_for_svg(svg_path: Path) -> Path | None:
    """返回 SVG 对应的预渲染 PNG 路径（若存在）。"""
    if svg_path.suffix.lower() == ".svg":
        png = SVG_PNG_DIR / svg_path.name.replace(".svg", ".png")
        if png.exists():
            return png
    return None


def image_page() -> None:
    section("增删设备对比图片")
    st.markdown('<p class="plain-note">两项对比成果：左侧为标准化美化图（调整前），右侧为增删设备后的验证图。</p>', unsafe_allow_html=True)
    groups = [
        ("LINE215 增加站房前后对比",
         SVG_DIR / "LINE215_beautified.svg", SVG_DIR / "LINE215_add_station_000300.svg",
         "调整前（美化图）", "增加站房后"),
        ("LINE216 删除开关前后对比",
         SVG_DIR / "LINE216_beautified.svg", SVG_DIR / "LINE216_del_switch_00024.svg",
         "调整前（美化图）", "删除开关后"),
    ]
    for title, before, after, before_label, after_label in groups:
        st.markdown(f"#### {title}")
        col1, col2 = st.columns(2, gap="large")
        with col1:
            st.caption(before_label)
            png_before = _png_for_svg(before)
            if png_before:
                st.image(str(png_before), use_container_width=True)
                with open(png_before, "rb") as f:
                    st.download_button("📥 下载 PNG", f.read(), png_before.name, mime="image/png", use_container_width=True)
            elif before.exists():
                raw = prepare_inline_svg(before.read_bytes())
                components.html(f'<div class="svgbox" style="height:520px;overflow:auto">{raw}</div>', height=560, scrolling=True)
            else:
                st.info(f"尚未生成：{before.name}")
        with col2:
            st.caption(after_label)
            png_after = _png_for_svg(after)
            if png_after:
                st.image(str(png_after), use_container_width=True)
                with open(png_after, "rb") as f:
                    st.download_button("📥 下载 PNG", f.read(), png_after.name, mime="image/png", use_container_width=True)
            elif after.exists():
                raw = prepare_inline_svg(after.read_bytes())
                components.html(f'<div class="svgbox" style="height:520px;overflow:auto">{raw}</div>', height=560, scrolling=True)
            else:
                st.info(f"尚未生成：{after.name}")


def submission_page() -> None:
    section("竞赛提交内容")
    submission_items = [
        (
            "5.1 现有 SVG 图形标准化美化排版",
            [SVG_DIR / "LINE215_beautified.svg", SVG_DIR / "LINE216_beautified.svg"],
            "LINE215、LINE216 标准化美化图及修正图",
        ),
        (
            "5.2 SVG 图形交互式增删设备",
            [SVG_DIR / "LINE215_add_station_000300.svg", SVG_DIR / "LINE216_del_switch_00024.svg"],
            "增加站房、删除开关的 SVG 验证图（左右即前后对比）",
        ),
        (
            "5.3 自动生成 SVG 接线图",
            [SVG_DIR / "LINE215_single_line.svg", SVG_DIR / "LINE216_single_line.svg", SVG_DIR / "10kVLINE111_tie.svg", SVG_DIR / "SUB004_station_tie.svg", SVG_DIR / "TMP00034205_power_trace.svg"],
            "单线图、联络图、全站图、电源追溯图",
        ),
    ]
    for index, (title, files, desc) in enumerate(submission_items, start=1):
        st.markdown(f'<div class="file-row"><b>{html.escape(title)}</b><br><span class="plain-note">{html.escape(desc)}</span></div>', unsafe_allow_html=True)
        available = [path for path in files if path.exists()]
        if available:
            archive_name = f"{title.replace(' ', '')}.zip"
            st.download_button(
                "下载本项成果",
                zip_files(available),
                archive_name,
                mime="application/zip",
                key=f"submission_zip_{index}",
                use_container_width=True,
            )
        else:
            st.caption("运行相应图形任务后，本项成果会显示在这里。")

    excel_files = generated_excel_files()
    st.markdown('<div class="file-row"><b>拓扑校验问题标准输出</b><br><span class="plain-note">程序运行后自动生成的线路 Excel 报告</span></div>', unsafe_allow_html=True)
    if excel_files:
        for index, path in enumerate(excel_files):
            cols = st.columns([0.72, 0.28])
            with cols[0]:
                st.markdown(f'<div class="file-row"><span class="tag">Excel</span>{html.escape(path.name)}　{path.stat().st_size / 1024:.1f} KB</div>', unsafe_allow_html=True)
            with cols[1]:
                st.download_button(
                    "下载表格",
                    path.read_bytes(),
                    path.name,
                    mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    key=f"submission_excel_{index}_{path.name}",
                    use_container_width=True,
                )
    else:
        st.info("运行主程序后，生成的 Excel 报告会显示在这里。")
    section("对应赛题任务")
    task_df = pd.DataFrame([
        ["任务一", "拓扑结构完整性", "悬空检测、断点定位、联络开关识别、合环检测", "缺陷报告、专项断点报告"],
        ["任务二", "图模一致性", "图有模无、模有图无、连接关系不一致", "缺陷清单、质量评分"],
        ["任务三", "修正与复核", "最小修改候选、影响分析、修复后复核", "候选报告、SQL 脚本、Excel"],
        ["任务四", "SVG 图形专项", "标准化美化、单线图、联络图、电源追溯图", "修正 SVG 与专题图集"],
    ], columns=["任务", "内容", "完成方式", "提交成果"])
    st.dataframe(task_df, use_container_width=True, hide_index=True)
    section("成果文件一览")
    groups = [
        ("线路报告", sorted(OUTPUT.glob("*.xlsx"))),
        ("分析报告", sorted(OUTPUT.glob("*.json"))),
        ("修复脚本", sorted(OUTPUT.glob("*.sql"))),
        ("SVG 图形", sorted(SVG_DIR.glob("*.svg"))),
        ("校验摘要", sorted(REPORT_DIR.glob("*.json"))),
    ]
    for name, paths in groups:
        with st.expander(f"{name}　{len(paths)} 项", expanded=name == "线路报告"):
            for path in paths:
                st.markdown(f'<div class="file-row">{html.escape(path.name)}</div>', unsafe_allow_html=True)


def main() -> None:
    st.set_page_config(page_title="主配网拓扑校验与图形成果展示", page_icon="⚡", layout="wide")
    style()
    with st.sidebar:
        st.markdown("### 成果展示")
        page = st.radio("页面", ["项目概览", "线路成果", "SVG 图纸", "对比图片", "提交内容"], label_visibility="collapsed")
        st.markdown("---")
        st.caption("电力拓扑与图模校验技术竞赛")
        st.caption("展示数据：LINE215、LINE216 及专题图形")
    header()
    if page == "项目概览":
        overview_page()
    elif page == "线路成果":
        line_page()
    elif page == "SVG 图纸":
        svg_page()
    elif page == "对比图片":
        image_page()
    else:
        submission_page()


if __name__ == "__main__":
    main()
