-- ==========================================================
-- Phase 2 Test Task 1：新增站房 000300 + 3 台负荷开关 + 拓扑连接
-- 目标SVG：LINE215_beautified.svg (开关 00104 ↔ 00102 之间插入)
-- 生成时间：auto-generated by task_deliverables.py
-- 可回滚：每一条 INSERT 都提供对应 DELETE (ROLLBACK段)
-- ==========================================================
BEGIN TRANSACTION;

-- 1. 新增站房（站房容器）
INSERT INTO EQUIP_JBS_PWROOM (ROOM_ID, ROOM_NAME, ROOM_TYPE, VOLTAGE_TYPE, REMARK)
VALUES ('TMPROOM000300', '站房000300', '开闭所', 'lkv10', 'LINE215测试任务新增');

-- 2. 新增 3 台负荷开关 (站房内)
INSERT INTO EQUIP_JBS_PWEQUIPINFO (EQUIP_ID, EQUIP_NAME, EQUIP_TYPE, VOLTAGE_TYPE, FEEDER_ID, DSUBSTATION_ID, PSR_TYPE, REMARK) VALUES
  ('TMP00301', '开关00301', '负荷开关', 'lkv10', 'LINE215', 'TMPROOM000300', '0307', '站房000300-上游对接开关'),
  ('TMP00302', '开关00302', '负荷开关', 'lkv10', 'LINE215', 'TMPROOM000300', '0307', '站房000300-备用间隔'),
  ('TMP00303', '开关00303', '负荷开关', 'lkv10', 'LINE215', 'TMPROOM000300', '0307', '站房000300-下游对接开关');

-- 3. 新增馈线段：开关00104 → 00301；开关00301 → 00303；开关00303 → 00102；备用分支 00301→00302
INSERT INTO EQUIP_JBS_PWFEEDERLINE (LINE_ID, LINE_NAME, START_ST_ID, END_ST_ID, VOLTAGE_TYPE, FEEDER_ID, LINE_TYPE, REMARK) VALUES
  ('LN_00104_00301', '开关00104-开关00301', 'TMP00044018', 'TMP00301', 'lkv10', 'LINE215', 'Trunk', '站房000300上游引入'),
  ('LN_00301_00303', '开关00301-开关00303', 'TMP00301', 'TMP00303', 'lkv10', 'LINE215', 'Trunk', '站房000300主干贯通'),
  ('LN_00303_00102', '开关00303-开关00102', 'TMP00303', 'TMP00044016', 'lkv10', 'LINE215', 'Trunk', '站房000300下游引出'),
  ('LN_00301_00302', '开关00301-开关00302_备用', 'TMP00301', 'TMP00302', 'lkv10', 'LINE215', 'Spare', '备用间隔引线(备用死端)');

COMMIT;

-- ========================= ROLLBACK（若需撤销） =========================
-- BEGIN TRANSACTION;
-- DELETE FROM EQUIP_JBS_PWFEEDERLINE WHERE LINE_ID IN ('LN_00104_00301','LN_00301_00303','LN_00303_00102','LN_00301_00302');
-- DELETE FROM EQUIP_JBS_PWEQUIPINFO   WHERE EQUIP_ID  IN ('TMP00301','TMP00302','TMP00303');
-- DELETE FROM EQUIP_JBS_PWROOM        WHERE ROOM_ID   =  'TMPROOM000300';
-- COMMIT;
