INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1001,'1000kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1002,'750kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1003,'500kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1004,'330kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1005,'220kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1006,'110kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1007,'66kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1008,'35kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1009,'20kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1010,'10kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1011,'6kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1012,'3kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1013,'0.4kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(1099,'ÖÐÐÔµã');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(3009,'13.8kV');
INSERT INTO "EQUIP"."JBS_VOLTAGETYPE"("VOLTAGE_ID","VOLTAGE_NAME") VALUES(3019,'6.3kV');

