"""
Phase 2 + Phase 3 成果产出总入口 v1
====================================

本模块独立完成两个任务：

Task A (Phase 2 交互式编辑):
  1. LINE215_beautified.svg：插入站房 000300，内含开关 00301/00302/00303
     规则：开关00104 ↔ 00301，开关00303 ↔ 00102，00302 备用间隔
  2. LINE216_beautified.svg：删除开关 00024，两侧设备直接连通
  3. 产出：
       output/svg/LINE215_beautified_with_000300.svg
       output/svg/LINE216_beautified_del_00024.svg
       output/sql/edit_add_station_000300.sql   — 可回滚SQL草案
       output/sql/edit_del_switch_00024.sql      — 可回滚SQL草案
       output/json/edit_*.json                    — 前后拓扑差异与验证报告

Task B (Phase 3 自动生成 SVG 4 类图):
  基于 SQL 拓扑 (EQUIP_JBS_PWEQUIPINFO.sql + EQUIP_JBS_PWFEEDERLINE.sql)：
  1. 单馈线单线图：LINE215 / LINE216
  2. 馈线联络关系图：10kVLINE111
  3. 全站联络总图：SUB004 变电站下所有馈线间联络
  4. 电源追溯路径图：LINE074 配变 TMP00034205（主供+备供）

每个阶段输出：1) SVG 文件 2) 生成元数据 JSON（节点/边/误差%） 3) 浏览器可打开
本文件被 run_pipeline.py 引用，也可以单独：python -m svg_io.task_deliverables
"""
from __future__ import annotations

import json
import os
import sys
from typing import Any

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from config.settings import OUTPUT_SVG, OUTPUT_JSON, OUTPUT_SQL, TEST_SVG_ROOT

from svg_io.svg_beautifier import SvgBeautifier
from svg_io.svg_editor import SvgInteractiveEditorV2
from svg_io.quality_checker import check_svg_quality
from data_io.svg_reader import SvgDocument


# ----------------------------------------------------------------
# Task A：交互式编辑（LINE215 + LINE216）+ SQL 草案 + 差异报告
# ----------------------------------------------------------------
def _sql_quote(v: Any) -> str:
    if v is None:
        return "NULL"
    return "'" + str(v).replace("'", "''") + "'"


def run_task_a() -> dict:
    """执行编辑任务并输出所有成果。"""
    os.makedirs(OUTPUT_SVG, exist_ok=True)
    os.makedirs(OUTPUT_SQL, exist_ok=True)
    os.makedirs(OUTPUT_JSON, exist_ok=True)

    reports = {}

    # ---- A1. LINE215 插入站房 000300 ----
    line215_src = os.path.join(TEST_SVG_ROOT, "LINE215.svg")
    line215_out = os.path.join(OUTPUT_SVG, "LINE215_add_station_000300.svg")

    b1 = SvgBeautifier(line215_src, output_path=line215_out)
    b1._prepare_internal_data()
    b1.repair()
    b1.layout()

    # 用 beautifier 内部数据统计编辑前（避免重新解析美化后SVG导致计数异常）
    def _count_internal(b):
        real_devs = [p for p, d in b.devices.items() if b.is_real_device(d['type'])]
        conns = sum(len(v) for v in b.adj.values()) // 2
        return {"devices": len(real_devs), "stations": len(b.containers), "connections": conns}

    pre_stat = _count_internal(b1)
    editor = SvgInteractiveEditorV2(b1)
    editor.add_station(
        station_id="000300",
        station_name="站房000300",
        upstream_query="TMP00044018",       # 开关 00104 对应 SVG 内 id
        downstream_query="TMP00044016",     # 开关 00102 对应 SVG 内 id
        internal_switch_ids=["00301", "00302", "00303"],
    )
    # relayout=True：add_station 已修改 adj，必须重建生成树，
    # 否则 _draw_wires 用旧树画线，新增开关没有 WIRE_ 连线（图实不一致）
    editor.save(line215_out, relayout=True)
    post_stat = _count_internal(b1)

    # 质量验证
    ok_a1, rep_a1 = check_svg_quality(
        line215_out, os.path.join(OUTPUT_JSON, "LINE215_with_000300_质量报告.json"))

    # 生成 SQL 草案：新增站房 + 3 开关 + 连接关系
    add_sql = f"""-- ==========================================================
-- Phase 2 Test Task 1：新增站房 000300 + 3 台负荷开关 + 拓扑连接
-- 目标SVG：LINE215_beautified.svg (开关 00104 ↔ 00102 之间插入)
-- 生成时间：auto-generated by task_deliverables.py
-- 可回滚：每一条 INSERT 都提供对应 DELETE (ROLLBACK段)
-- ==========================================================
BEGIN TRANSACTION;

-- 1. 新增站房（站房容器）
-- 【列名对齐真实表】JBS_PWROOM 真实列：ROOM_ID,ROOM_NAME,TOP_VOLTAGE_TYPE,FEEDER_ID,TYPE
INSERT INTO "EQUIP"."JBS_PWROOM" (ROOM_ID, ROOM_NAME, TOP_VOLTAGE_TYPE, FEEDER_ID, TYPE)
VALUES ({_sql_quote('TMPROOM000300')}, {_sql_quote('站房000300')}, '1010', {_sql_quote('LINE215')}, '开闭所');

-- 2. 新增 3 台负荷开关 (站房内)
-- JBS_PWEQUIPINFO 真实列：EQUIP_ID,EQUIP_NAME,EQUIP_TYPE,VOLTAGE_TYPE,FEEDER_ID,DSUBSTATION_ID,COMPOSITESWITCH
INSERT INTO "EQUIP"."JBS_PWEQUIPINFO" (EQUIP_ID, EQUIP_NAME, EQUIP_TYPE, VOLTAGE_TYPE, FEEDER_ID, DSUBSTATION_ID) VALUES
  # SVG 中 editor.add_station 生成的开关 id 为 SW_ 前缀（svg_editor.py: SW_ + 短ID），SQL 必须与图实一致
  ({_sql_quote('SW_00301')}, {_sql_quote('开关00301')}, '负荷开关', '1010', {_sql_quote('LINE215')}, {_sql_quote('TMPROOM000300')}),
  ({_sql_quote('SW_00302')}, {_sql_quote('开关00302')}, '负荷开关', '1010', {_sql_quote('LINE215')}, {_sql_quote('TMPROOM000300')}),
  ({_sql_quote('SW_00303')}, {_sql_quote('开关00303')}, '负荷开关', '1010', {_sql_quote('LINE215')}, {_sql_quote('TMPROOM000300')});

-- 3. 新增馈线段：开关00104 → 00301；开关00301 → 00303；开关00303 → 00102；备用分支 00301→00302
-- 【列名对齐真实表】JBS_PWFEEDERLINE 真实列仅 LINE_ID,LINE_NAME,START_ST_ID,VOLTAGE_TYPE（无 END_ST_ID）；
--    连接关系经 JBS_PWTERMINAL.CONNECTIVITYNODE_ID 表达（同一节点即连通）
INSERT INTO "EQUIP"."JBS_PWFEEDERLINE" (LINE_ID, LINE_NAME, START_ST_ID, VOLTAGE_TYPE) VALUES
  ({_sql_quote('LN_00104_00301')}, {_sql_quote('开关00104-开关00301')}, {_sql_quote('TMP00044018')}, '1010'),
  ({_sql_quote('LN_00301_00303')}, {_sql_quote('开关00301-开关00303')}, {_sql_quote('SW_00301')}, '1010'),
  ({_sql_quote('LN_00303_00102')}, {_sql_quote('开关00303-开关00102')}, {_sql_quote('SW_00303')}, '1010'),
  ({_sql_quote('LN_00301_00302')}, {_sql_quote('开关00301-开关00302_备用')}, {_sql_quote('SW_00301')}, '1010');
-- 连接关系（端子接入同一CONNECTIVITYNODE_ID即连通）
INSERT INTO "EQUIP"."JBS_PWTERMINAL" (ID, EQUIP_ID, CONNECTIVITYNODE_ID) VALUES
  ({_sql_quote('TMPT001')}, {_sql_quote('SW_00301')}, 'CN_00301_UP'),
  ({_sql_quote('TMPT002')}, {_sql_quote('SW_00301')}, 'CN_00301_DOWN'),
  ({_sql_quote('TMPT003')}, {_sql_quote('SW_00302')}, 'CN_00301_DOWN'),
  ({_sql_quote('TMPT004')}, {_sql_quote('SW_00303')}, 'CN_00301_DOWN'),
  ({_sql_quote('TMPT005')}, {_sql_quote('SW_00303')}, 'CN_00303_DOWN');

COMMIT;

-- ========================= ROLLBACK（若需撤销） =========================
-- BEGIN TRANSACTION;
-- DELETE FROM "EQUIP"."JBS_PWTERMINAL"    WHERE EQUIP_ID  IN ('SW_00301','SW_00302','SW_00303');
-- DELETE FROM "EQUIP"."JBS_PWFEEDERLINE" WHERE LINE_ID IN ('LN_00104_00301','LN_00301_00303','LN_00303_00102','LN_00301_00302');
-- DELETE FROM "EQUIP"."JBS_PWEQUIPINFO"   WHERE EQUIP_ID  IN ('SW_00301','SW_00302','SW_00303');
-- DELETE FROM "EQUIP"."JBS_PWROOM"        WHERE ROOM_ID   =  'TMPROOM000300';
-- COMMIT;
"""
    sql_path_a1 = os.path.join(OUTPUT_SQL, "edit_add_station_000300.sql")
    with open(sql_path_a1, "w", encoding="utf-8") as f:
        f.write(add_sql)

    diff_a1 = {
        "SVG_before": os.path.abspath(line215_src),
        "SVG_after": os.path.abspath(line215_out),
        "SQL_draft": os.path.abspath(sql_path_a1),
        "quality_pass": ok_a1,
        "pre": pre_stat,
        "post": post_stat,
        "delta": {k: post_stat[k] - pre_stat[k] for k in pre_stat},
        "expect_delta": {"devices": +3, "stations": +1, "connections": +4},
    }
    with open(os.path.join(OUTPUT_JSON, "edit_add_station_000300_diff.json"), "w", encoding="utf-8") as f:
        json.dump(diff_a1, f, ensure_ascii=False, indent=2)
    reports["A1_LINE215_add_station_000300"] = diff_a1

    # ---- A2. LINE216 删除开关 00024 ----
    line216_src = os.path.join(TEST_SVG_ROOT, "LINE216.svg")
    line216_out = os.path.join(OUTPUT_SVG, "LINE216_del_switch_00024.svg")

    b2 = SvgBeautifier(line216_src, output_path=line216_out)
    b2._prepare_internal_data()
    b2.repair()
    b2.layout()

    def _count_internal2(b):
        real_devs = [p for p, d in b.devices.items() if b.is_real_device(d['type'])]
        conns = sum(len(v) for v in b.adj.values()) // 2
        return {"devices": len(real_devs), "connections": conns}

    pre_stat2 = _count_internal2(b2)
    editor2 = SvgInteractiveEditorV2(b2)
    editor2.delete_device("TMP00043912")  # 开关 00024
    # relayout=True：删除后 adj 已更新（两侧桥接），重建生成树使 WIRE_ 连线反映桥接
    editor2.save(line216_out, relayout=True)
    post_stat2 = _count_internal2(b2)

    ok_a2, rep_a2 = check_svg_quality(
        line216_out, os.path.join(OUTPUT_JSON, "LINE216_del_00024_质量报告.json"))

    del_sql = f"""-- ==========================================================
-- Phase 2 Test Task 2：删除开关 00024 (SVG id=TMP00043912)
-- 目标SVG：LINE216_beautified.svg
-- 【列名对齐真实表】连通性只由 "EQUIP"."JBS_PWTERMINAL"(ID,EQUIP_ID,CONNECTIVITYNODE_ID) 表达：
--   JBS_PWFEEDERLINE 无 END_ST_ID（仅 LINE_ID,LINE_NAME,START_ST_ID,VOLTAGE_TYPE），
--   因此"两侧直通"用"给两侧邻居设备接入同一新连通节点 CN_BRIDGE_00024"实现，不写馈线行。
-- 策略：1) 找与 TMP00043912 共享连通节点的邻居 → 2) 邻居端子接入新节点（直通）
--       3) 删设备端子 → 4) 删设备本体
-- 可回滚：ROLLBACK 段恢复设备并删除桥接端子。
-- ==========================================================
BEGIN TRANSACTION;

-- 1. 桥接：为所有与 TMP00043912 共享连通节点的邻居设备插入新端子，接入同一新节点 CN_BRIDGE_00024
--   （等价于"开关删除后两侧设备直接连通"；NOT EXISTS 防重复执行）
INSERT INTO "EQUIP"."JBS_PWTERMINAL" (ID, EQUIP_ID, CONNECTIVITYNODE_ID)
SELECT 'TMPT_BRIDGE_' || NEI.EQUIP_ID, NEI.EQUIP_ID, 'CN_BRIDGE_00024'
FROM (
    SELECT DISTINCT T2.EQUIP_ID
    FROM "EQUIP"."JBS_PWTERMINAL" T1
    JOIN "EQUIP"."JBS_PWTERMINAL" T2
      ON T1.CONNECTIVITYNODE_ID = T2.CONNECTIVITYNODE_ID
    WHERE T1.EQUIP_ID = 'TMP00043912'
      AND T2.EQUIP_ID <> 'TMP00043912'
) NEI
WHERE NOT EXISTS (
    SELECT 1 FROM "EQUIP"."JBS_PWTERMINAL" X
    WHERE X.EQUIP_ID = NEI.EQUIP_ID
      AND X.CONNECTIVITYNODE_ID = 'CN_BRIDGE_00024'
);

-- 2. 删除开关本体的端子
DELETE FROM "EQUIP"."JBS_PWTERMINAL" WHERE EQUIP_ID = 'TMP00043912';

-- 3. 删除开关本体设备
DELETE FROM "EQUIP"."JBS_PWEQUIPINFO" WHERE EQUIP_ID = 'TMP00043912';

COMMIT;

-- ========================= ROLLBACK（若需撤销） =========================
-- 1. 恢复设备本体（JBS_PWEQUIPINFO 真实列；DSUBSTATION_ID 按实际站房补）
-- INSERT INTO "EQUIP"."JBS_PWEQUIPINFO" (EQUIP_ID, EQUIP_NAME, EQUIP_TYPE, VOLTAGE_TYPE, FEEDER_ID, DSUBSTATION_ID)
-- VALUES ('TMP00043912','开关00024','负荷开关','1010','LINE216','<实际站房ID>');
-- 2. 删除桥接端子（撤销直通，恢复原端子分配需按实际桥接ID补充）
-- DELETE FROM "EQUIP"."JBS_PWTERMINAL" WHERE CONNECTIVITYNODE_ID = 'CN_BRIDGE_00024';
"""
    sql_path_a2 = os.path.join(OUTPUT_SQL, "edit_del_switch_00024.sql")
    with open(sql_path_a2, "w", encoding="utf-8") as f:
        f.write(del_sql)

    diff_a2 = {
        "SVG_before": os.path.abspath(line216_src),
        "SVG_after": os.path.abspath(line216_out),
        "SQL_draft": os.path.abspath(sql_path_a2),
        "quality_pass": ok_a2,
        "pre": pre_stat2,
        "post": post_stat2,
        "delta": {k: post_stat2[k] - pre_stat2[k] for k in pre_stat2},
        "expect_delta": {"devices": -1, "connections": "±k (删除关联连接并+1桥接，期望净变化≈-1)"},
    }
    with open(os.path.join(OUTPUT_JSON, "edit_del_switch_00024_diff.json"), "w", encoding="utf-8") as f:
        json.dump(diff_a2, f, ensure_ascii=False, indent=2)
    reports["A2_LINE216_del_switch_00024"] = diff_a2

    return reports


# ----------------------------------------------------------------
# Task B：自动出图 4 类 5 张 SVG
# ----------------------------------------------------------------
from svg_io.svg_auto_generator import SvgAutoGenerator  # noqa: E402

def run_task_b() -> dict:
    os.makedirs(OUTPUT_SVG, exist_ok=True)
    os.makedirs(OUTPUT_JSON, exist_ok=True)

    g = SvgAutoGenerator()
    results: dict[str, dict] = {}

    # B1. LINE215 单线图
    p = g.generate_feeder_single_line_diagram(feeder_name="LINE215",
        out_path=os.path.join(OUTPUT_SVG, "LINE215_single_line.svg"))
    results["B1_LINE215_单线图"] = p

    # B2. LINE216 单线图
    p = g.generate_feeder_single_line_diagram(feeder_name="LINE216",
        out_path=os.path.join(OUTPUT_SVG, "LINE216_single_line.svg"))
    results["B2_LINE216_单线图"] = p

    # B3. 10kVLINE111 联络关系图
    p = g.generate_feeder_tie_diagram(feeder_name="10kVLINE111",
        out_path=os.path.join(OUTPUT_SVG, "10kVLINE111_tie.svg"))
    results["B3_10kVLINE111_联络关系图"] = p

    # B4. SUB004 全站馈线联络总图
    p = g.generate_station_tie_diagram(substation_id="SUB004",
        out_path=os.path.join(OUTPUT_SVG, "SUB004_station_tie.svg"))
    results["B4_SUB004_全站联络总图"] = p

    # B5. LINE074 配变 TMP00034205 电源追溯路径图（含备供）
    p = g.generate_power_trace_diagram(
        target_equip_id="TMP00034205",
        feeder_name="LINE074",
        out_path=os.path.join(OUTPUT_SVG, "TMP00034205_power_trace.svg"))
    results["B5_LINE074_TMP00034205_电源追溯"] = p

    # 输出汇总 JSON
    with open(os.path.join(OUTPUT_JSON, "auto_generate_summary.json"), "w", encoding="utf-8") as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    return results


# ----------------------------------------------------------------
# 统一 CLI
# ----------------------------------------------------------------
def main():
    print("=" * 72)
    print("Task A + B 交付物产出  (Phase 2 编辑 + Phase 3 自动出图)")
    print("=" * 72)
    a = run_task_a()
    print("\n[Task A 完成] 编辑成果：")
    for k, v in a.items():
        print(f"  {k}: PASS={v['quality_pass']}  Δ={v['delta']}  SVG={v['SVG_after']}")
    b = run_task_b()
    print("\n[Task B 完成] 自动出图成果：")
    for k, v in b.items():
        print(f"  {k}: nodes={v.get('nodes')} edges={v.get('edges')} "
              f"error%={v.get('edge_error_pct')} SVG={v.get('svg')}")
    print("\n全部完成 ✔")
    return a, b


if __name__ == "__main__":
    main()
